#compdef wb-mcu-fw-updater

# AUTOMATICALLY GENERATED by https://github.com/tqdm/shtab
# Usage:
# 1) Copy this to a file named _wb-mcu-fw-updater (e.g. ~/.local/share/zsh_completion/_wb-mcu-fw-updater).
# 2) Add the following line to your .zshrc:
#    fpath=(~/.local/share/zsh_completion $fpath)
# See also: https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org


_shtab_wb_common_commands() {
  local _commands=(
    flash-file:'Directly flash firmware file'
    recover:'Restore the latest firmware on stuck in bootloader device.'
    recover-all:'Trying to recover all devices, added to wb-mqtt-serial'"'"'s config.'
    update-all:'Trying to update bootloaders and firmwares on all devices, enabled in wb-mqtt-serial'"'"'s config.'
    update-bl:'Update bootloader on single working device (to the suite-aware released version; downgrade/rollback allowed).'
    update-cmp:'Update components on single working device.'
    update-fw:'Update firmware on single working device.'
  )
  _describe 'wb-mcu-fw-updater commands' _commands
}

_shtab_wb_common_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_wb_common_defaults_added=0

_shtab_wb_common_flash_file_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--conn-settings[Connection settings to communicate with alive device (Default\: 9600N2)]:<connection_settings_str>:"
  {-u,--erase-uart}"[Erase device\'s uart settings\? (Default\: False)]"
  {-e,--erase-all}"[Erase ALL device\'s uart settings\? (Default\: False)]"
  "--file[File to flash]:<firmware_file>:"
  {-f,--force}"[Force updating all devices and answer \"Yes\" to all questions. (Default\: False)]"
  "--debug[Setting the least loglevel. (Default\: None)]"
  "--instrument[Connection backend for modbus calls. (Default\: pyserial)]:<connection backend>:(pyserial rpc)"
  "--broker[MQTT broker url. (Default\: unix\:\/\/\/var\/run\/mosquitto\/mosquitto.sock)]:<broker>:"
  {-T,--response-timeout}"[Modbus response timeout. (Default\: 0.2)]:<response_timeout>:"
  {-a,--slaveid}"[Slave address of the device.]:<slaveid>:(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247)"
  ":Serial port, device connected to.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_wb_common_flash_file_defaults_added=0

_shtab_wb_common_recover_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--fw-sig[Force specify device\'s firmware signature. (Default\: None)]:<fw_signature>:"
  "--restore-defaults[Erase all device\'s settings during flashing. (Default\: False)]"
  {-f,--force}"[Force updating all devices and answer \"Yes\" to all questions. (Default\: False)]"
  "--debug[Setting the least loglevel. (Default\: None)]"
  "--instrument[Connection backend for modbus calls. (Default\: pyserial)]:<connection backend>:(pyserial rpc)"
  "--broker[MQTT broker url. (Default\: unix\:\/\/\/var\/run\/mosquitto\/mosquitto.sock)]:<broker>:"
  {-T,--response-timeout}"[Modbus response timeout. (Default\: 0.2)]:<response_timeout>:"
  {-a,--slaveid}"[Slave address of the device.]:<slaveid>:(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247)"
  ":Serial port, device connected to.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_wb_common_recover_defaults_added=0

_shtab_wb_common_recover_all_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-T,--min-response-timeout}"[Minimal modbus response timeout. Actual response timeout is\: MAX(min_response_timeout, wb-mqtt-serial\'s response timeouts) (Default\: 0.5)]:<minimal_response_timeout>:"
  {-f,--force}"[Force updating all devices and answer \"Yes\" to all questions. (Default\: False)]"
  "--debug[Setting the least loglevel. (Default\: None)]"
  "--instrument[Connection backend for modbus calls. (Default\: pyserial)]:<connection backend>:(pyserial rpc)"
  "--broker[MQTT broker url. (Default\: unix\:\/\/\/var\/run\/mosquitto\/mosquitto.sock)]:<broker>:"
)

# guard to ensure default positional specs are added only once per session
_shtab_wb_common_recover_all_defaults_added=0

_shtab_wb_common_update_all_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--allow-downgrade[Firmware versions could be downgraded. (Default\: False)]"
  {-T,--min-response-timeout}"[Minimal modbus response timeout. Actual response timeout is\: MAX(min_response_timeout, wb-mqtt-serial\'s response timeouts) (Default\: 0.5)]:<minimal_response_timeout>:"
  {-f,--force}"[Force updating all devices and answer \"Yes\" to all questions. (Default\: False)]"
  "--debug[Setting the least loglevel. (Default\: None)]"
  "--instrument[Connection backend for modbus calls. (Default\: pyserial)]:<connection backend>:(pyserial rpc)"
  "--broker[MQTT broker url. (Default\: unix\:\/\/\/var\/run\/mosquitto\/mosquitto.sock)]:<broker>:"
)

# guard to ensure default positional specs are added only once per session
_shtab_wb_common_update_all_defaults_added=0

_shtab_wb_common_update_bl_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-f,--force}"[Force updating all devices and answer \"Yes\" to all questions. (Default\: False)]"
  "--debug[Setting the least loglevel. (Default\: None)]"
  "--instrument[Connection backend for modbus calls. (Default\: pyserial)]:<connection backend>:(pyserial rpc)"
  "--broker[MQTT broker url. (Default\: unix\:\/\/\/var\/run\/mosquitto\/mosquitto.sock)]:<broker>:"
  {-T,--response-timeout}"[Modbus response timeout. (Default\: 0.2)]:<response_timeout>:"
  {-a,--slaveid}"[Slave address of the device.]:<slaveid>:(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247)"
  "--branch[Install from specified branch. (Default\: )]:<branch_name>:"
  "--version[Download a specified version. (Default\: None)]:<fw_version>:"
  ":Serial port, device connected to.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_wb_common_update_bl_defaults_added=0

_shtab_wb_common_update_cmp_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-f,--force}"[Force updating all devices and answer \"Yes\" to all questions. (Default\: False)]"
  "--debug[Setting the least loglevel. (Default\: None)]"
  "--instrument[Connection backend for modbus calls. (Default\: pyserial)]:<connection backend>:(pyserial rpc)"
  "--broker[MQTT broker url. (Default\: unix\:\/\/\/var\/run\/mosquitto\/mosquitto.sock)]:<broker>:"
  {-T,--response-timeout}"[Modbus response timeout. (Default\: 0.2)]:<response_timeout>:"
  {-a,--slaveid}"[Slave address of the device.]:<slaveid>:(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247)"
  "--branch[Install from specified branch. (Default\: )]:<branch_name>:"
  "--version[Download a specified version. (Default\: None)]:<fw_version>:"
  "--cmp-sig[Specify the signature of the component to update in case of branch or version specified.]:<component_signature>:"
  ":Serial port, device connected to.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_wb_common_update_cmp_defaults_added=0

_shtab_wb_common_update_fw_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--restore-defaults[Erase all device\'s settings during update. (Default\: False)]"
  {-f,--force}"[Force updating all devices and answer \"Yes\" to all questions. (Default\: False)]"
  "--debug[Setting the least loglevel. (Default\: None)]"
  "--instrument[Connection backend for modbus calls. (Default\: pyserial)]:<connection backend>:(pyserial rpc)"
  "--broker[MQTT broker url. (Default\: unix\:\/\/\/var\/run\/mosquitto\/mosquitto.sock)]:<broker>:"
  {-T,--response-timeout}"[Modbus response timeout. (Default\: 0.2)]:<response_timeout>:"
  {-a,--slaveid}"[Slave address of the device.]:<slaveid>:(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247)"
  "--branch[Install from specified branch. (Default\: )]:<branch_name>:"
  "--version[Download a specified version. (Default\: None)]:<fw_version>:"
  ":Serial port, device connected to.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_wb_common_update_fw_defaults_added=0


_shtab_wb_common() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*:' default='*::: :->wb-mcu-fw-updater'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_wb_common_defaults_added )); then
    if (( ${_shtab_wb_common_options[(I)${(q)one_or_more}*]} +          ${_shtab_wb_common_options[(I)${(q)remainder}*]} +          ${_shtab_wb_common_options[(I)${(q)default}]} == 0 )); then
      _shtab_wb_common_options+=(': :_shtab_wb_common_commands' '*::: :->wb-mcu-fw-updater')
    fi
    _shtab_wb_common_defaults_added=1
  fi
  _arguments -C -s $_shtab_wb_common_options

  case $state in
    wb-mcu-fw-updater)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_wb_common-$line[1]:"
      case $line[1] in
        flash-file) _arguments -C -s $_shtab_wb_common_flash_file_options ;;
        recover) _arguments -C -s $_shtab_wb_common_recover_options ;;
        recover-all) _arguments -C -s $_shtab_wb_common_recover_all_options ;;
        update-all) _arguments -C -s $_shtab_wb_common_update_all_options ;;
        update-bl) _arguments -C -s $_shtab_wb_common_update_bl_options ;;
        update-cmp) _arguments -C -s $_shtab_wb_common_update_cmp_options ;;
        update-fw) _arguments -C -s $_shtab_wb_common_update_fw_options ;;
      esac
  esac
}



typeset -A opt_args

if [[ $zsh_eval_context[-1] == eval ]]; then
  # eval/source/. command, register function for later
  compdef _shtab_wb_common -N wb-mcu-fw-updater
else
  # autoload from fpath, call function directly
  _shtab_wb_common "$@"
fi

