# AUTOMATICALLY GENERATED by https://github.com/tqdm/shtab
# Usage:
# 1) Copy this to ~/.config/fish/completions/wb-mcu-fw-updater.fish
# 2) Ensure a binary named wb-mcu-fw-updater is in your PATH
# See also: https://fishshell.com/docs/current/completions.html#where-to-put-completions


# Parse current commandline:
# - _shtab_wb_common_cmdpath=(sub)command path seen so far
# - _shtab_wb_common_npos=number of positional arguments given after it
# - options are skipped based on _shtab_wb_common_opts_with_value & _shtab_wb_common_commands lists
function _shtab_wb_common_scan
  set -g _shtab_wb_common_cmdpath ''
  set -g _shtab_wb_common_npos 0
  set -l tokens (commandline -opc)
  set -e tokens[1]
  set -l expect_value 0
  for t in $tokens
    if test $expect_value -eq 1
      set expect_value 0
      continue
    end
    switch "$t"
      case '--*=*'
        continue
      case '-*'
        if contains -- $t $_shtab_wb_common_opts_with_value
          set expect_value 1
        end
        continue
      case '*'
        if test $_shtab_wb_common_npos -eq 0
          set -l candidate $t
          if test -n "$_shtab_wb_common_cmdpath"
            set candidate "$_shtab_wb_common_cmdpath $t"
          end
          if contains -- $candidate $_shtab_wb_common_commands
            set -g _shtab_wb_common_cmdpath $candidate
            continue
          end
        end
        set -g _shtab_wb_common_npos (math $_shtab_wb_common_npos + 1)
    end
  end
end

# Condition helper: true if the current (sub)command path equals the given one.
function _shtab_wb_common_using
  _shtab_wb_common_scan
  test "$_shtab_wb_common_cmdpath" = "$argv"
end

set -g _shtab_wb_common_commands update-fw update-bl update-cmp recover update-all recover-all flash-file
set -g _shtab_wb_common_opts_with_value --branch --broker --cmp-sig --conn-settings --file --fw-sig --instrument --min-response-timeout --response-timeout --slaveid --version -T -a

complete -c wb-mcu-fw-updater -e
complete -c wb-mcu-fw-updater -f

complete -c wb-mcu-fw-updater -n _shtab_wb_common_using -s h -l help -d 'show this help message and exit'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using; and test $_shtab_wb_common_npos -eq 0' -a update-fw -d 'Update firmware on single working device.'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-fw' -s h -l help -d 'show this help message and exit'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-fw' -l restore-defaults -d 'Erase all device'"'"'s settings during update. (Default: False)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-fw' -s f -l force -d 'Force updating all devices and answer "Yes" to all questions. (Default: False)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-fw' -l debug -d 'Setting the least loglevel. (Default: None)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-fw' -l instrument -xka "pyserial rpc" -d 'Connection backend for modbus calls. (Default: pyserial)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-fw' -l broker -x -d 'MQTT broker url. (Default: unix:///var/run/mosquitto/mosquitto.sock)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-fw' -s T -l response-timeout -x -d 'Modbus response timeout. (Default: 0.2)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-fw' -s a -l slaveid -xka "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247" -d 'Slave address of the device.'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-fw' -l branch -x -d 'Install from specified branch. (Default: )'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-fw' -l version -x -d 'Download a specified version. (Default: None)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using; and test $_shtab_wb_common_npos -eq 0' -a update-bl -d 'Update bootloader on single working device (to the suite-aware released version; downgrade/rollback allowed).'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-bl' -s h -l help -d 'show this help message and exit'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-bl' -s f -l force -d 'Force updating all devices and answer "Yes" to all questions. (Default: False)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-bl' -l debug -d 'Setting the least loglevel. (Default: None)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-bl' -l instrument -xka "pyserial rpc" -d 'Connection backend for modbus calls. (Default: pyserial)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-bl' -l broker -x -d 'MQTT broker url. (Default: unix:///var/run/mosquitto/mosquitto.sock)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-bl' -s T -l response-timeout -x -d 'Modbus response timeout. (Default: 0.2)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-bl' -s a -l slaveid -xka "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247" -d 'Slave address of the device.'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-bl' -l branch -x -d 'Install from specified branch. (Default: )'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-bl' -l version -x -d 'Download a specified version. (Default: None)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using; and test $_shtab_wb_common_npos -eq 0' -a update-cmp -d 'Update components on single working device.'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-cmp' -s h -l help -d 'show this help message and exit'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-cmp' -s f -l force -d 'Force updating all devices and answer "Yes" to all questions. (Default: False)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-cmp' -l debug -d 'Setting the least loglevel. (Default: None)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-cmp' -l instrument -xka "pyserial rpc" -d 'Connection backend for modbus calls. (Default: pyserial)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-cmp' -l broker -x -d 'MQTT broker url. (Default: unix:///var/run/mosquitto/mosquitto.sock)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-cmp' -s T -l response-timeout -x -d 'Modbus response timeout. (Default: 0.2)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-cmp' -s a -l slaveid -xka "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247" -d 'Slave address of the device.'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-cmp' -l branch -x -d 'Install from specified branch. (Default: )'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-cmp' -l version -x -d 'Download a specified version. (Default: None)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-cmp' -l cmp-sig -x -d 'Specify the signature of the component to update in case of branch or version specified.'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using; and test $_shtab_wb_common_npos -eq 0' -a recover -d 'Restore the latest firmware on stuck in bootloader device.'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using recover' -s h -l help -d 'show this help message and exit'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using recover' -l fw-sig -x -d 'Force specify device'"'"'s firmware signature. (Default: None)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using recover' -l restore-defaults -d 'Erase all device'"'"'s settings during flashing. (Default: False)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using recover' -s f -l force -d 'Force updating all devices and answer "Yes" to all questions. (Default: False)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using recover' -l debug -d 'Setting the least loglevel. (Default: None)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using recover' -l instrument -xka "pyserial rpc" -d 'Connection backend for modbus calls. (Default: pyserial)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using recover' -l broker -x -d 'MQTT broker url. (Default: unix:///var/run/mosquitto/mosquitto.sock)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using recover' -s T -l response-timeout -x -d 'Modbus response timeout. (Default: 0.2)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using recover' -s a -l slaveid -xka "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247" -d 'Slave address of the device.'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using; and test $_shtab_wb_common_npos -eq 0' -a update-all -d 'Trying to update bootloaders and firmwares on all devices, enabled in wb-mqtt-serial'"'"'s config.'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-all' -s h -l help -d 'show this help message and exit'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-all' -l allow-downgrade -d 'Firmware versions could be downgraded. (Default: False)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-all' -s T -l min-response-timeout -x -d 'Minimal modbus response timeout. Actual response timeout is: MAX(min_response_timeout, wb-mqtt-serial'"'"'s response timeouts) (Default: 0.5)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-all' -s f -l force -d 'Force updating all devices and answer "Yes" to all questions. (Default: False)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-all' -l debug -d 'Setting the least loglevel. (Default: None)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-all' -l instrument -xka "pyserial rpc" -d 'Connection backend for modbus calls. (Default: pyserial)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using update-all' -l broker -x -d 'MQTT broker url. (Default: unix:///var/run/mosquitto/mosquitto.sock)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using; and test $_shtab_wb_common_npos -eq 0' -a recover-all -d 'Trying to recover all devices, added to wb-mqtt-serial'"'"'s config.'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using recover-all' -s h -l help -d 'show this help message and exit'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using recover-all' -s T -l min-response-timeout -x -d 'Minimal modbus response timeout. Actual response timeout is: MAX(min_response_timeout, wb-mqtt-serial'"'"'s response timeouts) (Default: 0.5)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using recover-all' -s f -l force -d 'Force updating all devices and answer "Yes" to all questions. (Default: False)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using recover-all' -l debug -d 'Setting the least loglevel. (Default: None)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using recover-all' -l instrument -xka "pyserial rpc" -d 'Connection backend for modbus calls. (Default: pyserial)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using recover-all' -l broker -x -d 'MQTT broker url. (Default: unix:///var/run/mosquitto/mosquitto.sock)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using; and test $_shtab_wb_common_npos -eq 0' -a flash-file -d 'Directly flash firmware file'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using flash-file' -s h -l help -d 'show this help message and exit'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using flash-file' -l conn-settings -x -d 'Connection settings to communicate with alive device (Default: 9600N2)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using flash-file' -s u -l erase-uart -d 'Erase device'"'"'s uart settings? (Default: False)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using flash-file' -s e -l erase-all -d 'Erase ALL device'"'"'s uart settings? (Default: False)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using flash-file' -l file -x -d 'File to flash'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using flash-file' -s f -l force -d 'Force updating all devices and answer "Yes" to all questions. (Default: False)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using flash-file' -l debug -d 'Setting the least loglevel. (Default: None)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using flash-file' -l instrument -xka "pyserial rpc" -d 'Connection backend for modbus calls. (Default: pyserial)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using flash-file' -l broker -x -d 'MQTT broker url. (Default: unix:///var/run/mosquitto/mosquitto.sock)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using flash-file' -s T -l response-timeout -x -d 'Modbus response timeout. (Default: 0.2)'
complete -c wb-mcu-fw-updater -n '_shtab_wb_common_using flash-file' -s a -l slaveid -xka "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247" -d 'Slave address of the device.'

